#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x4E7160ED4AC8EE1D (michael@stapelberg.de)
#
Name     : i3lock
Version  : 2.10
Release  : 4
URL      : https://i3wm.org/i3lock/i3lock-2.10.tar.bz2
Source0  : https://i3wm.org/i3lock/i3lock-2.10.tar.bz2
Source99 : https://i3wm.org/i3lock/i3lock-2.10.tar.bz2.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: i3lock-bin
Requires: i3lock-license
Requires: i3lock-data
BuildRequires : Linux-PAM-dev
BuildRequires : libev-dev
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(xcb-atom)
BuildRequires : pkgconfig(xcb-image)
BuildRequires : pkgconfig(xcb-randr)
BuildRequires : pkgconfig(xcb-xinerama)
BuildRequires : pkgconfig(xcb-xkb)
BuildRequires : pkgconfig(xkbcommon)
BuildRequires : pkgconfig(xkbcommon-x11)
Patch1: 0001-fix-include-libev.diff

%description
i3lock - improved screen locker
===============================
i3lock is a simple screen locker like slock. After starting it, you will
see a white screen (you can configure the color/an image). You can return
to your screen by entering your password.

%package bin
Summary: bin components for the i3lock package.
Group: Binaries
Requires: i3lock-data
Requires: i3lock-license

%description bin
bin components for the i3lock package.


%package data
Summary: data components for the i3lock package.
Group: Data

%description data
data components for the i3lock package.


%package license
Summary: license components for the i3lock package.
Group: Default

%description license
license components for the i3lock package.


%prep
%setup -q -n i3lock-2.10
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1528943843
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1528943843
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/i3lock
cp LICENSE %{buildroot}/usr/share/doc/i3lock/LICENSE
%make_install
## make_install_append content
mkdir -p %{buildroot}/usr/share/pam.d
mv %{buildroot}/etc/pam.d/*  %{buildroot}/usr/share/pam.d
## make_install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/i3lock

%files data
%defattr(-,root,root,-)
/usr/share/pam.d/i3lock

%files license
%defattr(-,root,root,-)
/usr/share/doc/i3lock/LICENSE
